# Generated by Django 5.2.12 on 2026-03-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('estimated_end_date', models.DateField(verbose_name='Fecha Estimada de Finalización')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('on_hold', 'En Pausa'), ('completed', 'Completado')], default='active', max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(help_text='Ej: Ingeniero CAD, Gerente de Calidad', max_length=150, verbose_name='Rol en el Proyecto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='projects.project')),
            ],
            options={
                'verbose_name': 'Asignación de Proyecto',
                'verbose_name_plural': 'Asignaciones de Proyectos',
            },
        ),
    ]
