# Generated by Django 5.2.12 on 2026-03-23 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Lunes de la semana que se reporta', verbose_name='Inicio de Semana')),
                ('percentage_allocated', models.DecimalField(decimal_places=2, help_text='Porcentaje de la capacidad semanal asignado (0.0 a 100.0)', max_digits=5, verbose_name='Porcentaje Reportado (%)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_records', to='projects.project', verbose_name='Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro Semanal',
                'verbose_name_plural': 'Registros Semanales',
                'unique_together': {('user', 'project', 'week_start_date')},
            },
        ),
    ]
